"""the schema as it stands at v0.1

Revision ID: ca187a896ff4
Revises:
Create Date: 2026-08-31 00:20:22.877095
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# 自作の型（`UtcDateTime`）と方言固有の型（JSONB）を下の定義が参照する。
import aijudge_persistence.schema

revision: str = "ca187a896ff4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_tokens",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("note", sa.String(length=256), nullable=False),
        sa.Column(
            "created_at", aijudge_persistence.schema.UtcDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "expires_at", aijudge_persistence.schema.UtcDateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "revoked_at", aijudge_persistence.schema.UtcDateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "last_used_at", aijudge_persistence.schema.UtcDateTime(timezone=True), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_tokens_created_at"), "api_tokens", ["created_at"], unique=False)
    op.create_index(op.f("ix_api_tokens_revoked_at"), "api_tokens", ["revoked_at"], unique=False)
    op.create_index(op.f("ix_api_tokens_tenant_id"), "api_tokens", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_api_tokens_token_hash"), "api_tokens", ["token_hash"], unique=True)
    op.create_index(op.f("ix_api_tokens_user_id"), "api_tokens", ["user_id"], unique=False)
    op.create_table(
        "blind_marks",
        sa.Column("submission_id", sa.String(length=64), nullable=False),
        sa.Column("grader_id", sa.String(length=64), nullable=False),
        sa.Column(
            "marked_at", aijudge_persistence.schema.UtcDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("submission_id"),
    )
    op.create_index(op.f("ix_blind_marks_grader_id"), "blind_marks", ["grader_id"], unique=False)
    op.create_table(
        "courses",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("term", sa.String(length=64), nullable=False),
        sa.Column("subject_profile", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "rubric",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "grading_overrides",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("auto_finalize_after_minutes", sa.Integer(), nullable=True),
        sa.Column(
            "upload_suffixes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "late_penalty_steps",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "code", "term", name="uq_courses_code_term"),
    )
    op.create_index(
        op.f("ix_courses_subject_profile"), "courses", ["subject_profile"], unique=False
    )
    op.create_index(op.f("ix_courses_tenant_id"), "courses", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_courses_term"), "courses", ["term"], unique=False)
    op.create_table(
        "finalizations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("grading_run_id", sa.String(length=64), nullable=False),
        sa.Column("submission_id", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=True),
        sa.Column(
            "finalized_at", aijudge_persistence.schema.UtcDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("grading_run_id", name="uq_finalizations_run"),
    )
    op.create_index(op.f("ix_finalizations_actor_id"), "finalizations", ["actor_id"], unique=False)
    op.create_index(
        op.f("ix_finalizations_finalized_at"), "finalizations", ["finalized_at"], unique=False
    )
    op.create_index(
        op.f("ix_finalizations_grading_run_id"), "finalizations", ["grading_run_id"], unique=False
    )
    op.create_index(op.f("ix_finalizations_source"), "finalizations", ["source"], unique=False)
    op.create_index(
        op.f("ix_finalizations_submission_id"), "finalizations", ["submission_id"], unique=False
    )
    op.create_table(
        "grading_jobs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("submission_id", sa.String(length=64), nullable=False),
        sa.Column("subject_profile", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("phase", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=192), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "available_at", aijudge_persistence.schema.UtcDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "lease_expires_at", aijudge_persistence.schema.UtcDateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "created_at", aijudge_persistence.schema.UtcDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", aijudge_persistence.schema.UtcDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_jobs_idempotency_key"),
    )
    op.create_index(op.f("ix_grading_jobs_phase"), "grading_jobs", ["phase"], unique=False)
    op.create_index(
        op.f("ix_grading_jobs_submission_id"), "grading_jobs", ["submission_id"], unique=False
    )
    op.create_index(op.f("ix_grading_jobs_tenant_id"), "grading_jobs", ["tenant_id"], unique=False)
    op.create_index("ix_jobs_available", "grading_jobs", ["state", "available_at"], unique=False)
    op.create_index(
        "ix_jobs_phase_available", "grading_jobs", ["phase", "state", "available_at"], unique=False
    )
    op.create_index(
        "ix_jobs_profile_state", "grading_jobs", ["subject_profile", "state"], unique=False
    )
    op.create_table(
        "grading_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("submission_id", sa.String(length=64), nullable=False),
        sa.Column("task_version_id", sa.String(length=64), nullable=False),
        sa.Column("subject_profile", sa.String(length=64), nullable=False),
        sa.Column("input_hash", sa.String(length=128), nullable=False),
        sa.Column("score_ratio", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("routing", sa.String(length=32), nullable=False),
        sa.Column("superseded_by", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at", aijudge_persistence.schema.UtcDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_grading_runs_created_at"), "grading_runs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_grading_runs_input_hash"), "grading_runs", ["input_hash"], unique=False
    )
    op.create_index(op.f("ix_grading_runs_routing"), "grading_runs", ["routing"], unique=False)
    op.create_index(
        op.f("ix_grading_runs_subject_profile"), "grading_runs", ["subject_profile"], unique=False
    )
    op.create_index(
        op.f("ix_grading_runs_submission_id"), "grading_runs", ["submission_id"], unique=False
    )
    op.create_index(
        op.f("ix_grading_runs_task_version_id"), "grading_runs", ["task_version_id"], unique=False
    )
    op.create_index(
        "ix_runs_submission_created", "grading_runs", ["submission_id", "created_at"], unique=False
    )
    op.create_table(
        "human_reviews",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("grading_run_id", sa.String(length=64), nullable=False),
        sa.Column("submission_id", sa.String(length=64), nullable=False),
        sa.Column("grader_id", sa.String(length=64), nullable=False),
        sa.Column("agreed", sa.Boolean(), nullable=False),
        sa.Column(
            "reviewed_at", aijudge_persistence.schema.UtcDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("grading_run_id", name="uq_reviews_run"),
    )
    op.create_index(op.f("ix_human_reviews_agreed"), "human_reviews", ["agreed"], unique=False)
    op.create_index(
        op.f("ix_human_reviews_grader_id"), "human_reviews", ["grader_id"], unique=False
    )
    op.create_index(
        op.f("ix_human_reviews_grading_run_id"), "human_reviews", ["grading_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_human_reviews_reviewed_at"), "human_reviews", ["reviewed_at"], unique=False
    )
    op.create_index(
        op.f("ix_human_reviews_submission_id"), "human_reviews", ["submission_id"], unique=False
    )
    op.create_table(
        "knowledge_components",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("namespace", sa.String(length=64), nullable=False),
        sa.Column("key", sa.String(length=256), nullable=False),
        sa.Column("label", sa.String(length=256), nullable=False),
        sa.Column("parent_id", sa.String(length=64), nullable=True),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", name="uq_kc_key"),
    )
    op.create_index(
        op.f("ix_knowledge_components_key"), "knowledge_components", ["key"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_components_namespace"),
        "knowledge_components",
        ["namespace"],
        unique=False,
    )
    op.create_table(
        "outbox_events",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column(
            "occurred_at", aijudge_persistence.schema.UtcDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "published_at", aijudge_persistence.schema.UtcDateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_outbox_events_occurred_at"), "outbox_events", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_events_published_at"), "outbox_events", ["published_at"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_events_tenant_id"), "outbox_events", ["tenant_id"], unique=False
    )
    op.create_index(op.f("ix_outbox_events_type"), "outbox_events", ["type"], unique=False)
    op.create_index(
        "ix_outbox_pending", "outbox_events", ["published_at", "occurred_at"], unique=False
    )
    op.create_table(
        "review_requests",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("grading_run_id", sa.String(length=64), nullable=False),
        sa.Column("submission_id", sa.String(length=64), nullable=False),
        sa.Column("learner_id", sa.String(length=64), nullable=False),
        sa.Column(
            "requested_at", aijudge_persistence.schema.UtcDateTime(timezone=True), nullable=False
        ),
        sa.Column("resolved_by", sa.String(length=64), nullable=True),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("grading_run_id", name="uq_requests_run"),
    )
    op.create_index(
        op.f("ix_review_requests_grading_run_id"),
        "review_requests",
        ["grading_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_requests_learner_id"), "review_requests", ["learner_id"], unique=False
    )
    op.create_index(
        op.f("ix_review_requests_requested_at"), "review_requests", ["requested_at"], unique=False
    )
    op.create_index(
        op.f("ix_review_requests_resolved_by"), "review_requests", ["resolved_by"], unique=False
    )
    op.create_index(
        op.f("ix_review_requests_submission_id"), "review_requests", ["submission_id"], unique=False
    )
    op.create_table(
        "skill_states",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("learner_id", sa.String(length=64), nullable=False),
        sa.Column("kc_id", sa.String(length=64), nullable=False),
        sa.Column("mastery", sa.Float(), nullable=False),
        sa.Column("model", sa.String(length=32), nullable=False),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at", aijudge_persistence.schema.UtcDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("tenant_id", "learner_id", "kc_id"),
    )
    op.create_index(
        op.f("ix_skill_states_updated_at"), "skill_states", ["updated_at"], unique=False
    )
    op.create_index(
        "ix_skill_tenant_learner", "skill_states", ["tenant_id", "learner_id"], unique=False
    )
    op.create_table(
        "submissions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("task_version_id", sa.String(length=64), nullable=False),
        sa.Column("learner_id", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", aijudge_persistence.schema.UtcDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "submitted_at", aijudge_persistence.schema.UtcDateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_submissions_learner_id"), "submissions", ["learner_id"], unique=False)
    op.create_index(
        "ix_submissions_learner_task",
        "submissions",
        ["tenant_id", "learner_id", "task_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_submissions_task_version_id"), "submissions", ["task_version_id"], unique=False
    )
    op.create_index(op.f("ix_submissions_tenant_id"), "submissions", ["tenant_id"], unique=False)
    op.create_table(
        "task_checks",
        sa.Column("task_version_id", sa.String(length=64), nullable=False),
        sa.Column("usable", sa.Boolean(), nullable=False),
        sa.Column(
            "checked_at", aijudge_persistence.schema.UtcDateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("task_version_id"),
    )
    op.create_index(op.f("ix_task_checks_usable"), "task_checks", ["usable"], unique=False)
    op.create_table(
        "task_embeddings",
        sa.Column("task_version_id", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("subject_profile", sa.String(length=64), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column(
            "vector",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("task_version_id", "model"),
    )
    op.create_index(
        op.f("ix_task_embeddings_subject_profile"),
        "task_embeddings",
        ["subject_profile"],
        unique=False,
    )
    op.create_table(
        "task_versions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("subject_profile", sa.String(length=64), nullable=False),
        sa.Column("review_state", sa.String(length=32), nullable=False),
        sa.Column("allow_handwriting", sa.Boolean(), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column(
            "created_at", aijudge_persistence.schema.UtcDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "version", name="uq_task_version"),
    )
    op.create_index(
        op.f("ix_task_versions_review_state"), "task_versions", ["review_state"], unique=False
    )
    op.create_index(
        op.f("ix_task_versions_subject_profile"), "task_versions", ["subject_profile"], unique=False
    )
    op.create_index(op.f("ix_task_versions_task_id"), "task_versions", ["task_id"], unique=False)
    op.create_index(
        "ix_task_versions_task_version", "task_versions", ["task_id", "version"], unique=False
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("course_id", sa.String(length=64), nullable=False),
        sa.Column("unit", sa.String(length=64), nullable=True),
        sa.Column("session", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column(
            "document",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_course_id"), "tasks", ["course_id"], unique=False)
    op.create_index(
        "ix_tasks_course_order", "tasks", ["course_id", "session", "position"], unique=False
    )
    op.create_index(op.f("ix_tasks_unit"), "tasks", ["unit"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("login", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=256), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at", aijudge_persistence.schema.UtcDateTime(timezone=True), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "login", name="uq_users_tenant_login"),
    )
    op.create_index(op.f("ix_users_state"), "users", ["state"], unique=False)
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_table(
        "enrollments",
        sa.Column("course_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("course_id", "user_id"),
    )
    op.create_index(op.f("ix_enrollments_role"), "enrollments", ["role"], unique=False)
    op.create_index(op.f("ix_enrollments_tenant_id"), "enrollments", ["tenant_id"], unique=False)
    op.create_index("ix_enrollments_user", "enrollments", ["tenant_id", "user_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at", aijudge_persistence.schema.UtcDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "expires_at", aijudge_persistence.schema.UtcDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "revoked_at", aijudge_persistence.schema.UtcDateTime(timezone=True), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash", name="uq_sessions_token_hash"),
    )
    op.create_index(op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_sessions_tenant_id"), "sessions", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "submission_keys",
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("submission_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
        ),
        sa.PrimaryKeyConstraint("tenant_id", "idempotency_key"),
    )
    op.create_index(
        op.f("ix_submission_keys_submission_id"), "submission_keys", ["submission_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_submission_keys_submission_id"), table_name="submission_keys")
    op.drop_table("submission_keys")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_tenant_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("ix_enrollments_user", table_name="enrollments")
    op.drop_index(op.f("ix_enrollments_tenant_id"), table_name="enrollments")
    op.drop_index(op.f("ix_enrollments_role"), table_name="enrollments")
    op.drop_table("enrollments")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_index(op.f("ix_users_state"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tasks_unit"), table_name="tasks")
    op.drop_index("ix_tasks_course_order", table_name="tasks")
    op.drop_index(op.f("ix_tasks_course_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("ix_task_versions_task_version", table_name="task_versions")
    op.drop_index(op.f("ix_task_versions_task_id"), table_name="task_versions")
    op.drop_index(op.f("ix_task_versions_subject_profile"), table_name="task_versions")
    op.drop_index(op.f("ix_task_versions_review_state"), table_name="task_versions")
    op.drop_table("task_versions")
    op.drop_index(op.f("ix_task_embeddings_subject_profile"), table_name="task_embeddings")
    op.drop_table("task_embeddings")
    op.drop_index(op.f("ix_task_checks_usable"), table_name="task_checks")
    op.drop_table("task_checks")
    op.drop_index(op.f("ix_submissions_tenant_id"), table_name="submissions")
    op.drop_index(op.f("ix_submissions_task_version_id"), table_name="submissions")
    op.drop_index("ix_submissions_learner_task", table_name="submissions")
    op.drop_index(op.f("ix_submissions_learner_id"), table_name="submissions")
    op.drop_table("submissions")
    op.drop_index("ix_skill_tenant_learner", table_name="skill_states")
    op.drop_index(op.f("ix_skill_states_updated_at"), table_name="skill_states")
    op.drop_table("skill_states")
    op.drop_index(op.f("ix_review_requests_submission_id"), table_name="review_requests")
    op.drop_index(op.f("ix_review_requests_resolved_by"), table_name="review_requests")
    op.drop_index(op.f("ix_review_requests_requested_at"), table_name="review_requests")
    op.drop_index(op.f("ix_review_requests_learner_id"), table_name="review_requests")
    op.drop_index(op.f("ix_review_requests_grading_run_id"), table_name="review_requests")
    op.drop_table("review_requests")
    op.drop_index("ix_outbox_pending", table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_type"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_tenant_id"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_published_at"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_occurred_at"), table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index(op.f("ix_knowledge_components_namespace"), table_name="knowledge_components")
    op.drop_index(op.f("ix_knowledge_components_key"), table_name="knowledge_components")
    op.drop_table("knowledge_components")
    op.drop_index(op.f("ix_human_reviews_submission_id"), table_name="human_reviews")
    op.drop_index(op.f("ix_human_reviews_reviewed_at"), table_name="human_reviews")
    op.drop_index(op.f("ix_human_reviews_grading_run_id"), table_name="human_reviews")
    op.drop_index(op.f("ix_human_reviews_grader_id"), table_name="human_reviews")
    op.drop_index(op.f("ix_human_reviews_agreed"), table_name="human_reviews")
    op.drop_table("human_reviews")
    op.drop_index("ix_runs_submission_created", table_name="grading_runs")
    op.drop_index(op.f("ix_grading_runs_task_version_id"), table_name="grading_runs")
    op.drop_index(op.f("ix_grading_runs_submission_id"), table_name="grading_runs")
    op.drop_index(op.f("ix_grading_runs_subject_profile"), table_name="grading_runs")
    op.drop_index(op.f("ix_grading_runs_routing"), table_name="grading_runs")
    op.drop_index(op.f("ix_grading_runs_input_hash"), table_name="grading_runs")
    op.drop_index(op.f("ix_grading_runs_created_at"), table_name="grading_runs")
    op.drop_table("grading_runs")
    op.drop_index("ix_jobs_profile_state", table_name="grading_jobs")
    op.drop_index("ix_jobs_phase_available", table_name="grading_jobs")
    op.drop_index("ix_jobs_available", table_name="grading_jobs")
    op.drop_index(op.f("ix_grading_jobs_tenant_id"), table_name="grading_jobs")
    op.drop_index(op.f("ix_grading_jobs_submission_id"), table_name="grading_jobs")
    op.drop_index(op.f("ix_grading_jobs_phase"), table_name="grading_jobs")
    op.drop_table("grading_jobs")
    op.drop_index(op.f("ix_finalizations_submission_id"), table_name="finalizations")
    op.drop_index(op.f("ix_finalizations_source"), table_name="finalizations")
    op.drop_index(op.f("ix_finalizations_grading_run_id"), table_name="finalizations")
    op.drop_index(op.f("ix_finalizations_finalized_at"), table_name="finalizations")
    op.drop_index(op.f("ix_finalizations_actor_id"), table_name="finalizations")
    op.drop_table("finalizations")
    op.drop_index(op.f("ix_courses_term"), table_name="courses")
    op.drop_index(op.f("ix_courses_tenant_id"), table_name="courses")
    op.drop_index(op.f("ix_courses_subject_profile"), table_name="courses")
    op.drop_table("courses")
    op.drop_index(op.f("ix_blind_marks_grader_id"), table_name="blind_marks")
    op.drop_table("blind_marks")
    op.drop_index(op.f("ix_api_tokens_user_id"), table_name="api_tokens")
    op.drop_index(op.f("ix_api_tokens_token_hash"), table_name="api_tokens")
    op.drop_index(op.f("ix_api_tokens_tenant_id"), table_name="api_tokens")
    op.drop_index(op.f("ix_api_tokens_revoked_at"), table_name="api_tokens")
    op.drop_index(op.f("ix_api_tokens_created_at"), table_name="api_tokens")
    op.drop_table("api_tokens")
    # ### end Alembic commands ###
