"""let a rubric say how its criteria are folded

Revision ID: e23567ff5f36
Revises: df806c3a13b9
Create Date: 2026-08-31 02:11:43.695401
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql  # noqa: F401

# 自作の型（`UtcDateTime`）と方言固有の型（JSONB）を下の定義が参照する。
import aijudge_persistence.schema  # noqa: F401

revision: str = "e23567ff5f36"
down_revision: str | None = "df806c3a13b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("courses", sa.Column("rubric_aggregation", sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "rubric_aggregation")
    # ### end Alembic commands ###
