"""aiJudge core — 科目非依存のドメインモデルとイベント契約。

このパッケージは全サブシステムが依存してよい唯一の層であり、
逆にこのパッケージは他のどのパッケージにも依存しない（P1 / P9）。
依存方向は `.importlinter` の contract で CI が強制する。

ここに入れてよいもの:
  - 科目に依存しない語彙（Task / Submission / GradingRun / KC / Skill / Credential）
  - サブシステム間のイベント契約
  - 上記に閉じた純粋な規則（集約、状態遷移、妥当性検査）

ここに入れてはいけないもの:
  - 「コードか数式かレポートか」の知識 → evaluators/ へ
  - I/O（DB・HTTP・LLM・ファイル）    → 各 packages/ へ
"""

from __future__ import annotations

from .access import in_audience, may_see, may_submit_before_open
from .events import (
    EVENT_TYPES,
    SCHEMA_VERSION,
    CredentialIssued,
    DomainEvent,
    GradingCompleted,
    SkillStateUpdated,
    SubmissionCreated,
    TaskPublished,
)
from .extraction import (
    Extraction,
    Extractor,
)
from .finalization import (
    AUTOMATIC_JUSTIFICATION,
    Finalization,
    FinalizationSource,
    GradeWindow,
    auto_finalizable,
    blocks_finalization,
    bulk_finalizable,
    grace_minutes,
    grade_window,
    settles_at,
)
from .grading import (
    GATE_ZERO,
    MIN_JUSTIFICATION_LENGTH,
    BlindMark,
    CriterionScore,
    EvaluatorKind,
    EvaluatorResult,
    EvaluatorStatus,
    FinalScore,
    GradingContext,
    GradingPhase,
    GradingRun,
    HumanReview,
    KcOutcome,
    LatePenalty,
    LatePenaltyStep,
    ReviewPolicy,
    ReviewRequest,
    Routing,
    aggregate,
    final_score,
    gate_skipped,
    late_penalty_for,
    penalty_crosses_boundary,
    renormalize,
    resolve_conflicts,
    score_withheld,
)
from .ids import derived_id, new_id, prefix_of
from .knowledge import (
    KnowledgeComponent,
    QMatrixEntry,
    is_valid_kc_key,
    kc_id_for,
    parse_kc_key,
)
from .network import CampusAccess, campus_access, parse_cidrs
from .retention import (
    AUTOSAVE_RETENTION_MONTHS_AFTER_CLOSE,
    PURGED_MESSAGE,
    VIDEO_RETENTION_MONTHS,
    VIDEO_RETENTION_MONTHS_WITHOUT_DEADLINE,
    autosave_expires_at,
    video_retention_expires_at,
    video_retention_has_expired,
)
from .skill import (
    Credential,
    CredentialExport,
    MasteryModel,
    SkillEvidence,
    SkillPoint,
    SkillState,
)
from .spans import (
    ArtifactSpan,
    CharSpan,
    CriterionEvidence,
    Evidence,
    LineSpan,
    RegionSpan,
    WholeSpan,
)
from .submission import (
    Artifact,
    ArtifactKind,
    ArtifactRole,
    Submission,
    SubmissionState,
    TranscriptionMeta,
    assert_transition,
    can_transition,
)
from .task import (
    HUMAN_SCORED,
    Aggregation,
    AnswerMode,
    Provenance,
    ReviewState,
    RubricCriterion,
    RubricLevel,
    SubmissionWindow,
    Task,
    TaskVersion,
    TestCase,
    effective_aggregation,
    effective_max_score,
    max_scores_by_version,
)
from .tenancy import MAX_GROUP_NAME_LENGTH, Course, CourseGroup, Enrollment, Role, Tenant
from .terms import (
    DIVISIONS,
    YEARS_OFFERED,
    academic_year,
    format_term,
    is_valid_term,
    offered_years,
    parse_term,
    term_sort_key,
)
from .uploads import (
    ALL_UPLOAD_SUFFIXES,
    DEFAULT_UPLOAD_SUFFIXES,
    STREAMED_SUFFIXES,
    SUFFIX_GROUPS,
    SUFFIX_KINDS,
    allowed_suffixes,
    content_disposition,
    content_type_for,
    kind_for,
    normalize_suffixes,
)

__all__ = [
    "ALL_UPLOAD_SUFFIXES",
    "AUTOMATIC_JUSTIFICATION",
    "AUTOSAVE_RETENTION_MONTHS_AFTER_CLOSE",
    "DEFAULT_UPLOAD_SUFFIXES",
    "DIVISIONS",
    "EVENT_TYPES",
    "GATE_ZERO",
    "HUMAN_SCORED",
    "MAX_GROUP_NAME_LENGTH",
    "MIN_JUSTIFICATION_LENGTH",
    "PURGED_MESSAGE",
    "SCHEMA_VERSION",
    "STREAMED_SUFFIXES",
    "SUFFIX_GROUPS",
    "SUFFIX_KINDS",
    "VIDEO_RETENTION_MONTHS",
    "VIDEO_RETENTION_MONTHS_WITHOUT_DEADLINE",
    "YEARS_OFFERED",
    "Aggregation",
    "AnswerMode",
    "Artifact",
    "ArtifactKind",
    "ArtifactRole",
    "ArtifactSpan",
    "BlindMark",
    "CampusAccess",
    "CharSpan",
    "Course",
    "CourseGroup",
    "Credential",
    "CredentialExport",
    "CredentialIssued",
    "CriterionEvidence",
    "CriterionScore",
    "DomainEvent",
    "Enrollment",
    "EvaluatorKind",
    "EvaluatorResult",
    "EvaluatorStatus",
    "Evidence",
    "Extraction",
    "Extractor",
    "FinalScore",
    "Finalization",
    "FinalizationSource",
    "GradeWindow",
    "GradingCompleted",
    "GradingContext",
    "GradingPhase",
    "GradingRun",
    "HumanReview",
    "KcOutcome",
    "KnowledgeComponent",
    "LatePenalty",
    "LatePenaltyStep",
    "LineSpan",
    "MasteryModel",
    "Provenance",
    "QMatrixEntry",
    "RegionSpan",
    "ReviewPolicy",
    "ReviewRequest",
    "ReviewState",
    "Role",
    "Routing",
    "RubricCriterion",
    "RubricLevel",
    "SkillEvidence",
    "SkillPoint",
    "SkillState",
    "SkillStateUpdated",
    "Submission",
    "SubmissionCreated",
    "SubmissionState",
    "SubmissionWindow",
    "Task",
    "TaskPublished",
    "TaskVersion",
    "Tenant",
    "TestCase",
    "TranscriptionMeta",
    "WholeSpan",
    "academic_year",
    "aggregate",
    "allowed_suffixes",
    "assert_transition",
    "auto_finalizable",
    "autosave_expires_at",
    "blocks_finalization",
    "bulk_finalizable",
    "campus_access",
    "can_transition",
    "content_disposition",
    "content_type_for",
    "derived_id",
    "effective_aggregation",
    "effective_max_score",
    "final_score",
    "format_term",
    "gate_skipped",
    "grace_minutes",
    "grade_window",
    "in_audience",
    "is_valid_kc_key",
    "is_valid_term",
    "kc_id_for",
    "kind_for",
    "late_penalty_for",
    "max_scores_by_version",
    "may_see",
    "may_submit_before_open",
    "new_id",
    "normalize_suffixes",
    "offered_years",
    "parse_cidrs",
    "parse_kc_key",
    "parse_term",
    "penalty_crosses_boundary",
    "prefix_of",
    "renormalize",
    "resolve_conflicts",
    "score_withheld",
    "settles_at",
    "term_sort_key",
    "video_retention_expires_at",
    "video_retention_has_expired",
]
